name: Deploy Medusa to AWS ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 207268090422.dkr.ecr.us-east-1.amazonaws.com/medusa-backend
  ECS_CLUSTER: medusa-cluster
  ECS_SERVICE: medusa-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./Eks-terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Eks-terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./Eks-terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Tag Docker Image
      run: |
        docker build -t medusa-backend:latest .
        docker tag medusa-backend:latest $ECR_REPOSITORY:latest

    - name: Push Docker Image to ECR
      run: |
        docker push $ECR_REPOSITORY:latest

    - name: Deploy Updated Image to ECS
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment \
          --region $AWS_REGION
